[project]
name = "KARHU"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "f90nml>=1.4.4",
    "numpy==2.2.5",
    "scipy>=1.16.3",
    "torch==2.4.1",
]



[tool.setuptools]
# We want setuptools to treat `src` as the root for packages
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
# This replicates `find_packages(where="src")`
where = ["src"]

