[project]
name = "KARHU"
version = "0.1.1"
requires-python = ">=3.11"
dependencies = [
    "f90nml>=1.4.4",
    "numpy==2.2.5",
    "pytest>=9.0.1",
    "scipy>=1.16.3",
    "torch==2.4.1",
]
authors = [ {name="Amanda Bruncona", email="amanda.bruncona@vtt.fi"}, {name="Adam Kit", email="adam.kit@vtt.fi"}]



[tool.setuptools]
# We want setuptools to treat `src` as the root for packages
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
# This replicates `find_packages(where="src")`
where = ["src"]

